name: Artifacts

on:
  push:
    branches:
    - none

  workflow_dispatch:

jobs:

  stage-1:
    if: contains(toJson(github.event.commits), '/no-ci')
    name: Create file ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@master
    - run: mkdir -p path/to/artifact
    - run: echo "hello ${{ runner.os }}" > path/to/artifact/world.txt
    - run: echo "hello ${{ runner.os }}" > path/to/artifact/world2.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: path/to/artifact/

  stage-2:
    # if: contains(toJson(github.event.commits), '/no-ci') == false
    needs: [stage-1]
    name: Read file on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: path/to/artifact
      
    - run: ls -R path/to/artifact/
    - run: cat path/to/artifact/world.txt
    - run: cat path/to/artifact/world2.txt