name: Artifacts

on:
  push:
    branches:
    - main

  workflow_dispatch:

jobs:

  stage-1:
    # if: contains(toJson(github.event.commits), '/ut')
    name: Create file ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']

    outputs:
      ARTIFACT_FOLDER: path/to/artifact/

    env:
      ARTIFACT_FOLDER: path/to/artifact/


    steps:
    - uses: actions/checkout@master
    - run: mkdir -p ${{ ARTIFACT_FOLDER }}
    - run: echo "hello ${{ runner.os }}" > ${{ ARTIFACT_FOLDER }}/world.txt
    - run: echo "hello ${{ runner.os }}" > ${{ ARTIFACT_FOLDER }}/world2.txt

    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: "${{ ARTIFACT_FOLDER }}"

  stage-2:
    # if: contains(toJson(github.event.commits), '/no-ci') == false
    needs: [stage-1]
    name: Read file on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
    
    env:
      ARTIFACT_FOLDER: ${{ needs.stage-1.outputs.ARTIFACT_FOLDER }}

    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: my-artifact
        path: ${{ ARTIFACT_FOLDER }}
      
    - run: ls -R ${{ ARTIFACT_FOLDER }}/
    - run: cat ${{ ARTIFACT_FOLDER }}/world.txt
    - run: cat ${{ ARTIFACT_FOLDER }}/world2.txt