name: Installers

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - none

jobs:

  packaging:
    #if: contains(toJson(github.event.commits), '/no-ci') == false
    name: Package plugins on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [windows-2022]
        os: [macos-12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build win installer
      run: iscc installers/win/ci-cmake-juce.iss
    
    #- name: Download Packages installer
    #  run: wget http://s.sudre.free.fr/Software/files/Packages.dmg

    # - name: Install Packages
    #   run: sudo installer -pkg installers/mac/Packages.pkg -target /

    - name: Build mac-os installer
      run: packagesbuild installers/mac/ci-cmake-juce.pkgproj

    # install python for running the script
    - name: Setup Python and dependencies
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: |
        pip install firebase-admin

    # write the Credential json secrect key from git_secret
    - name: get secrect key
      id: write_key_file
      uses: timheuer/base64-to-file@v1
      with:
        fileName: '<KEY_FILE_NAME>.json' # name of the written key file
        encodedString: ${{ secrets.<SECRET_NAME> }} # Secret stored in Github secrets
    
    # run the upload script
    - name: run upload script
      run: python scripts/uploadInstallers.py # the path to upload script in the repository