name: Installers Mac

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  matrix_prep:
    #if: contains(toJson(github.event.commits), '/no-ci') == false && contains(toJson(github.event.commits), '/no-mac') == false
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2      
      - id: set-matrix
        uses: JoshuaTheMiller/conditional-build-matrix@main        
        with:
          inputFile: '.github/workflows/mac_matrix.json' # Default input file path
          filter: '[?runOnBranch==`${{ github.ref }}` || runOnBranch==`main`]'

  packaging:
    name: Packaging on ${{ matrix.runs_on }}
    #needs: [matrix_prep, build, sign]
    if: contains(toJson(github.event.commits), '/no-packaging') == false
    strategy:      
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    runs-on: ${{ matrix.runs_on }}
    #env:
    #  PLUGIN_NAME: ${{ needs.build.outputs.PLUGIN_NAME }}
    #  PLUGINS_FOLDER: ${{ needs.build.outputs.PLUGINS_FOLDER }}

    steps:
    - uses: actions/checkout@master
    - uses: actions/download-artifact@master
      with:
        name: plugins-folder-artifact
        path: ${PLUGINS_FOLDER}
  
    - name: Build Message
      run: echo "Starting packaging"

    - name: Build installer
      run: packagesbuild installers/mac/ci-cmake-juce.pkgproj
      