name: Installers Mac

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:

  packaging:
    if: contains(toJson(github.event.commits), '/no-ci') == false
    name: Package plugins on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
  
    - name: Build Message
      run: echo "Starting packaging"

    - name: Build installer
      run: packagesbuild installers/mac/ci-cmake-juce.pkgproj
      