name: Installers

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - none

jobs:

  packaging:
    #if: contains(toJson(github.event.commits), '/no-ci') == false
    name: Package plugins on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        #os: [windows-2022]
        os: [windows-2022]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: recursive
      
    #- name: Download Packages installer build tool
    #  run: wget http://s.sudre.free.fr/Software/files/Packages.dmg

    # - name: Install Packages
    #   run: sudo installer -pkg installers/mac/Packages.pkg -target /

    # - name: Build mac-os installer
    #   run: packagesbuild installers/mac/ci-cmake-juce.pkgproj

    - name: Build win installer
      run: iscc installers/win/ci-cmake-juce.iss
      