name: Variables

on: push

jobs:
  secrets:
    # if: contains(toJson(github.event.commits), '/ut')
    name: cast secrets
    runs-on: ubuntu-latest

    steps:
    - name: Run Unit Testing
      run: echo "${{ secrets.VALIDATORS.aax_win_validator.url }}"