name: Variables

on: push

jobs:
  test:
    name: testing
    runs-on: ubuntu-latest

    - name: Prepare pluginval 
      run: |
        curl -L "$PLUGINVAL_URL" -o pluginval.zip
        unzip pluginval > /dev/null
        echo "pluginval.app/Contents/MacOS/pluginval"
  
    - name: Prepare aaxval 
      run: |
        curl -L "${AAX_VAL_URL}&token=${AAX_VAL_TOKEN}" -o aax-sdk-2-4-0.zip
        ls
