name: Variables

on: 
  push:
    branches:
    - none

jobs:

  test:
    if: contains(toJson(github.event.commits), '/no-var-test') == false
    name: testing
    runs-on: ubuntu-latest
    outputs:
      GLOBAL_VAR: global_var
      PLUGIN_NAME: ci-juce-test
      PLUGINS_FOLDER: /Users/runner/Library/Audio/Plug-Ins/
    env:
      PLUGINVAL_MAC_URL: ${{ secrets.PLUGINVAL_MAC_URL }}
      AAXVAL_MAC_URL: ${{ secrets.AAXVAL_MAC_URL }}

    steps:
    - name: Prepare pluginval ${{ env.PLUGINVAL_MAC_URL }}
      run: |
        curl -L "${PLUGINVAL_MAC_URL}" -o pluginval.zip
        unzip pluginval > /dev/null
        echo "pluginval.app/Contents/MacOS/pluginval"
  
    - name: Prepare aaxval 
      run: |
        curl -L "${AAXVAL_MAC_URL}" -o aaxval_mac.zip
        unzip aaxval_mac > /dev/null
        ls -la
