name: Variables

on: push

jobs:
  test:
    name: testing
    runs-on: ubuntu-latest
    env:
      PLUGINVAL_MAC_URL: {{ secrets.PLUGINVAL_MAC_URL }}
      AAXVAL_MAC_URL: {{ secrets.AAXVAL_MAC_URL }}

    steps:
    - name: Prepare pluginval 
      run: |
        curl -L "${PLUGINVAL_MAC_URL}" -o pluginval.zip
        unzip pluginval > /dev/null
        echo "pluginval.app/Contents/MacOS/pluginval"
  
    - name: Prepare aaxval 
      run: |
        curl -L "${AAXVAL_MAC_URL}" -o aaxval_mac.zip
        unzip aaxval_mac > /dev/null
        ls -la
